<a href="https://colab.research.google.com/github/babatundeibukun/DEEP-LEARNING-PROJECT---COMPUTER/blob/main/building_simple_neural_network_with_tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import tensorflow as tf
import pandas as pd
from tensorflow import keras
import matplotlib.pyplot as plt

In [ ]:
df = pd.read_csv('insurance_data.csv')
df.head()

age  affordibility  bought_insurance
0   22              1                 0
1   25              0                 0
2   47              1                 1
3   52              0                 0
4   46              1                 1

In [ ]:
df.shape

(28, 3)

In [ ]:
from sklearn.model_selection  import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df[['age', 'affordibility']], df.bought_insurance, test_size= 0.2 , random_state=234)

In [ ]:
len(X_train)

22

In [ ]:
len(X_test)

6

In [ ]:
X_train.head()

age  affordibility
21   26              0
9    61              1
15   55              1
14   49              1
12   27              0

In [ ]:
X_train_scaled = X_train.copy()
X_train_scaled['age'] = X_train_scaled['age']/100

X_test_scaled = X_test.copy()
X_test_scaled['age'] = X_test_scaled['age']/100

In [ ]:
X_train_scaled.head()

age  affordibility
21  0.26              0
9   0.61              1
15  0.55              1
14  0.49              1
12  0.27              0

#Building a simple neural network with tensorflow

In [ ]:
model = keras.Sequential([
    keras.layers.Dense(1,input_shape=(2,), activation='sigmoid', kernel_initializer='ones', bias_initializer= 'zeros')
])

model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])

model.fit(X_train_scaled, y_train, epochs= 5000)

Epoch 1/5000


/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Streaming output truncated to the last 5000 lines.
Epoch 2501/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.8182 - loss: 0.5269
Epoch 2502/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.8182 - loss: 0.5268
Epoch 2503/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step - accuracy: 0.8182 - loss: 0.5268
Epoch 2504/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - accuracy: 0.8182 - loss: 0.5268
Epoch 2505/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.8182 - loss: 0.5267
Epoch 2506/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.8182 - loss: 0.5267
Epoch 2507/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.8182 - loss: 0.5267
Epoch 2508/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.8182 - loss: 0.5266
Epoch 2509/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - accuracy: 0.8182 - loss: 0.5266
Epoch 2510/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.8182 - loss: 0.5265
Epoch 2511/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step - accuracy: 0.8

To know how the model performs on an unseen data

In [17]:
model.evaluate(X_test_scaled, y_test)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 146ms/step - accuracy: 0.8333 - loss: 0.3861


[0.38605812191963196, 0.8333333134651184]

Now, lets predict

In [19]:
model.predict(X_test_scaled)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step


array([[0.31363264],
       [0.16882502],
       [0.26329112],
       [0.81411743],
       [0.60830307],
       [0.73593634]], dtype=float32)

In [20]:
y_test

10    0
18    0
13    0
17    1
6     0
24    1
Name: bought_insurance, dtype: int64

Now , I am so excited , I want to know my final weight and bias

In [21]:
coef, intercept = model.get_weights()
coef, intercept

(array([[5.6504507 ],
        [0.86729145]], dtype=float32),
 array([-2.6675632], dtype=float32))