<a href="https://colab.research.google.com/github/babatundeibukun/DEEP-LEARNING-PROJECT---COMPUTER/blob/main/Implenting_batch_gradient_descent.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [56]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [57]:
df = pd.read_csv('homeprices_banglore.csv')
df.head()

area  bedrooms   price
0  1056         2   39.07
1  2600         4  120.00
2  1440         3   62.00
3  1521         3   75.00
4  1200         2   51.00

In [58]:
df.shape

(20, 3)

In [59]:
df.isna().any()

area        False
bedrooms    False
price       False
dtype: bool

In [60]:
df.drop('price',axis=1)

area  bedrooms
0   1056         2
1   2600         4
2   1440         3
3   1521         3
4   1200         2
5   1170         2
6   2732         4
7   3300         4
8   1310         3
9   3700         5
10  1800         3
11  2785         4
12  1000         2
13  1100         2
14  2250         3
15  1175         2
16  1180         3
17  1540         3
18  2770         3
19   800         1

In [61]:
from sklearn import preprocessing
sx = preprocessing.MinMaxScaler()
sy = preprocessing.MinMaxScaler()

scaled_X = sx.fit_transform(df.drop('price',axis='columns'))
scaled_X

array([[0.08827586, 0.25      ],
       [0.62068966, 0.75      ],
       [0.22068966, 0.5       ],
       [0.24862069, 0.5       ],
       [0.13793103, 0.25      ],
       [0.12758621, 0.25      ],
       [0.6662069 , 0.75      ],
       [0.86206897, 0.75      ],
       [0.17586207, 0.5       ],
       [1.        , 1.        ],
       [0.34482759, 0.5       ],
       [0.68448276, 0.75      ],
       [0.06896552, 0.25      ],
       [0.10344828, 0.25      ],
       [0.5       , 0.5       ],
       [0.12931034, 0.25      ],
       [0.13103448, 0.5       ],
       [0.25517241, 0.5       ],
       [0.67931034, 0.5       ],
       [0.        , 0.        ]])

In [62]:
scaled_X.shape

(20, 2)

In [63]:
df.head()

area  bedrooms   price
0  1056         2   39.07
1  2600         4  120.00
2  1440         3   62.00
3  1521         3   75.00
4  1200         2   51.00

In [64]:
scaled_y = sy.fit_transform(df[['price']])
scaled_y

array([[0.05237037],
       [0.65185185],
       [0.22222222],
       [0.31851852],
       [0.14074074],
       [0.04444444],
       [0.76296296],
       [0.91111111],
       [0.13333333],
       [1.        ],
       [0.37037037],
       [0.8       ],
       [0.04444444],
       [0.05925926],
       [0.51111111],
       [0.07407407],
       [0.11851852],
       [0.20740741],
       [0.51851852],
       [0.        ]])

In [69]:
scaled_y.shape

(20, 1)

In [65]:
df.shape[1]

3

In [66]:
w = np.zeros(shape=(df.shape[1]))
w

array([0., 0., 0.])

In [72]:
#gradient_descent

def batch_gradient_descent(X, y, epochs) :
  number_of_features = scaled_X.shape[1]
  n = df.shape[0] #total_number_samples
  w = np.ones(shape=(number_of_features))
  bias = 0
  learning_rate = 0.01
  cost_list = []
  epoch_list = []

  for i in range(epochs):
    y_predicted = np.dot(scaled_X, w) + bias
    loss = np.square(y-y_predicted)
    wd = -(2/n) * np.dot(scaled_X.T,(y-y_predicted))
    bias_d = -(2/n)* np.sum(y-y_predicted)

    w = w - (learning_rate * wd)
    bias = bias - (learning_rate * bias_d)

    if i%10 :
      cost_list.append(loss)
      epoch_list.append(i)
  return w, bias, cost_list , epoch_list






In [73]:
w ,bias ,loss,  cost_list, epoch_list = batch_gradient_descent(scaled_X, scaled_y, 500)
w, bias, loss

ValueError: operands could not be broadcast together with shapes (2,) (2,20) 