<a href="https://colab.research.google.com/github/babatundeibukun/DEEP-LEARNING-PROJECT---COMPUTER/blob/main/Implenting_batch_gradient_descent.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [78]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [79]:
df = pd.read_csv('homeprices_banglore.csv')
df.head()

area  bedrooms   price
0  1056         2   39.07
1  2600         4  120.00
2  1440         3   62.00
3  1521         3   75.00
4  1200         2   51.00

In [80]:
df.shape

(20, 3)

In [81]:
df.isna().any()

area        False
bedrooms    False
price       False
dtype: bool

In [82]:
df.drop('price',axis=1)

area  bedrooms
0   1056         2
1   2600         4
2   1440         3
3   1521         3
4   1200         2
5   1170         2
6   2732         4
7   3300         4
8   1310         3
9   3700         5
10  1800         3
11  2785         4
12  1000         2
13  1100         2
14  2250         3
15  1175         2
16  1180         3
17  1540         3
18  2770         3
19   800         1

In [83]:
from sklearn import preprocessing
sx = preprocessing.MinMaxScaler()
sy = preprocessing.MinMaxScaler()

scaled_X = sx.fit_transform(df.drop('price',axis='columns'))
scaled_X

array([[0.08827586, 0.25      ],
       [0.62068966, 0.75      ],
       [0.22068966, 0.5       ],
       [0.24862069, 0.5       ],
       [0.13793103, 0.25      ],
       [0.12758621, 0.25      ],
       [0.6662069 , 0.75      ],
       [0.86206897, 0.75      ],
       [0.17586207, 0.5       ],
       [1.        , 1.        ],
       [0.34482759, 0.5       ],
       [0.68448276, 0.75      ],
       [0.06896552, 0.25      ],
       [0.10344828, 0.25      ],
       [0.5       , 0.5       ],
       [0.12931034, 0.25      ],
       [0.13103448, 0.5       ],
       [0.25517241, 0.5       ],
       [0.67931034, 0.5       ],
       [0.        , 0.        ]])

In [84]:
w =np.ones(shape=(2))
w

array([1., 1.])

In [85]:
np.dot(w, scaled_X.T)

array([0.33827586, 1.37068966, 0.72068966, 0.74862069, 0.38793103,
       0.37758621, 1.4162069 , 1.61206897, 0.67586207, 2.        ,
       0.84482759, 1.43448276, 0.31896552, 0.35344828, 1.        ,
       0.37931034, 0.63103448, 0.75517241, 1.17931034, 0.        ])

In [86]:
scaled_X.T

array([[0.08827586, 0.62068966, 0.22068966, 0.24862069, 0.13793103,
        0.12758621, 0.6662069 , 0.86206897, 0.17586207, 1.        ,
        0.34482759, 0.68448276, 0.06896552, 0.10344828, 0.5       ,
        0.12931034, 0.13103448, 0.25517241, 0.67931034, 0.        ],
       [0.25      , 0.75      , 0.5       , 0.5       , 0.25      ,
        0.25      , 0.75      , 0.75      , 0.5       , 1.        ,
        0.5       , 0.75      , 0.25      , 0.25      , 0.5       ,
        0.25      , 0.5       , 0.5       , 0.5       , 0.        ]])

In [87]:
scaled_X.shape

(20, 2)

In [88]:
scaled_X.T.shape

(2, 20)

In [89]:
w.shape

(2,)

In [90]:
np.dot(w, scaled_X.T)

array([0.33827586, 1.37068966, 0.72068966, 0.74862069, 0.38793103,
       0.37758621, 1.4162069 , 1.61206897, 0.67586207, 2.        ,
       0.84482759, 1.43448276, 0.31896552, 0.35344828, 1.        ,
       0.37931034, 0.63103448, 0.75517241, 1.17931034, 0.        ])

In [91]:
df.head()

area  bedrooms   price
0  1056         2   39.07
1  2600         4  120.00
2  1440         3   62.00
3  1521         3   75.00
4  1200         2   51.00

In [92]:
scaled_y = sy.fit_transform(df[['price']])
scaled_y

array([[0.05237037],
       [0.65185185],
       [0.22222222],
       [0.31851852],
       [0.14074074],
       [0.04444444],
       [0.76296296],
       [0.91111111],
       [0.13333333],
       [1.        ],
       [0.37037037],
       [0.8       ],
       [0.04444444],
       [0.05925926],
       [0.51111111],
       [0.07407407],
       [0.11851852],
       [0.20740741],
       [0.51851852],
       [0.        ]])

In [93]:
scaled_y.shape

(20, 1)

In [94]:
df.shape[1]

3

In [95]:
w = np.ones(shape=(df.shape[1]))
w

array([1., 1., 1.])

In [96]:
number_of_features = scaled_X.shape[1]
w = np.ones(shape=(number_of_features))
w


array([1., 1.])

In [97]:
scaled_X.shape

(20, 2)

In [98]:
np.dot(scaled_X , w)

array([0.33827586, 1.37068966, 0.72068966, 0.74862069, 0.38793103,
       0.37758621, 1.4162069 , 1.61206897, 0.67586207, 2.        ,
       0.84482759, 1.43448276, 0.31896552, 0.35344828, 1.        ,
       0.37931034, 0.63103448, 0.75517241, 1.17931034, 0.        ])

In [99]:
np.dot(w,scaled_X.T)

array([0.33827586, 1.37068966, 0.72068966, 0.74862069, 0.38793103,
       0.37758621, 1.4162069 , 1.61206897, 0.67586207, 2.        ,
       0.84482759, 1.43448276, 0.31896552, 0.35344828, 1.        ,
       0.37931034, 0.63103448, 0.75517241, 1.17931034, 0.        ])

In [100]:
np.dot(scaled_X , w).shape

(20,)

In [105]:
scaled_y = scaled_y.reshape(20,)
scaled_y

array([0.05237037, 0.65185185, 0.22222222, 0.31851852, 0.14074074,
       0.04444444, 0.76296296, 0.91111111, 0.13333333, 1.        ,
       0.37037037, 0.8       , 0.04444444, 0.05925926, 0.51111111,
       0.07407407, 0.11851852, 0.20740741, 0.51851852, 0.        ])

In [106]:
scaled_y.shape

(20,)

In [120]:
#gradient_descent

def batch_gradient_descent(X, y, epochs) :
  number_of_features = scaled_X.shape[1]
  n = df.shape[0] #total_number_samples
  w = np.ones(shape=(number_of_features))
  bias = 0
  learning_rate = 0.01
  cost_list = []
  epoch_list = []

  for i in range(epochs):
    y_predicted = np.dot(scaled_X, w) + bias
    loss = np.mean(np.square(y-y_predicted))
    wd = -(2/n) * (np.dot((y-y_predicted),scaled_X))
    bias_d = -(2/n)* np.sum(y-y_predicted)

    w = w - (learning_rate * wd)
    bias = bias - (learning_rate * bias_d)

    if i%10 :
      cost_list.append(loss)
      epoch_list.append(i)
  return w, bias, loss, cost_list , epoch_list






In [121]:
w ,bias ,loss,  cost_list, epoch_list = batch_gradient_descent(scaled_X, scaled_y, 500)
w, bias , loss

(array([0.70712464, 0.67456527]), -0.23034857438407427, 0.0068641890429808105)