<a href="https://colab.research.google.com/github/babatundeibukun/DEEP-LEARNING-PROJECT---COMPUTER/blob/main/practicing_regularization_to_prevent_overfitting.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [6]:
df = pd.read_csv('/content/sonar_dataset.csv', header = None)
df.head()

0       1       2       3       4       5   ...      55      56      57      58      59  60
0  0.0200  0.0371  0.0428  0.0207  0.0954  0.0986  ...  0.0167  0.0180  0.0084  0.0090  0.0032   R
1  0.0453  0.0523  0.0843  0.0689  0.1183  0.2583  ...  0.0191  0.0140  0.0049  0.0052  0.0044   R
2  0.0262  0.0582  0.1099  0.1083  0.0974  0.2280  ...  0.0244  0.0316  0.0164  0.0095  0.0078   R
3  0.0100  0.0171  0.0623  0.0205  0.0205  0.0368  ...  0.0073  0.0050  0.0044  0.0040  0.0117   R
4  0.0762  0.0666  0.0481  0.0394  0.0590  0.0649  ...  0.0015  0.0072  0.0048  0.0107  0.0094   R

[5 rows x 61 columns]

In [7]:
df.shape

(208, 61)

In [10]:
df.isna().sum()

0     0
1     0
2     0
3     0
4     0
     ..
56    0
57    0
58    0
59    0
60    0
Length: 61, dtype: int64

In [12]:
for columns in df :
  print(f'{columns} : {df[columns].unique()} ')

0 : [0.02   0.0453 0.0262 0.01   0.0762 0.0286 0.0317 0.0519 0.0223 0.0164
 0.0039 0.0123 0.0079 0.009  0.0124 0.0298 0.0352 0.0192 0.027  0.0126
 0.0473 0.0664 0.0099 0.0115 0.0293 0.0201 0.0151 0.0177 0.0189 0.024
 0.0084 0.0195 0.0442 0.0311 0.0206 0.0094 0.0333 0.0091 0.0068 0.0093
 0.0211 0.0257 0.0408 0.0308 0.0373 0.019  0.0119 0.0353 0.0131 0.0087
 0.0132 0.0152 0.0216 0.0225 0.0125 0.013  0.0135 0.0086 0.0067 0.0071
 0.0176 0.0265 0.0368 0.0065 0.0036 0.0208 0.0139 0.0109 0.0202 0.0239
 0.0336 0.0231 0.0108 0.0229 0.0409 0.0217 0.0378 0.0365 0.0188 0.0856
 0.0274 0.0235 0.0253 0.026  0.0459 0.0025 0.0291 0.0181 0.0491 0.1313
 0.0629 0.0335 0.0587 0.0162 0.0307 0.0116 0.0331 0.0428 0.0599 0.0264
 0.021  0.053  0.0454 0.0283 0.0114 0.0414 0.0228 0.0363 0.0261 0.0346
 0.0249 0.0388 0.0715 0.0209 0.0374 0.1371 0.0443 0.115  0.0968 0.079
 0.1083 0.1088 0.043  0.0731 0.0412 0.0707 0.0526 0.0516 0.0299 0.0721
 0.1021 0.0654 0.0712 0.0207 0.0233 0.0117 0.0047 0.0107 0.0258 0.0305
 0.0

In [13]:
df.dtypes

0     float64
1     float64
2     float64
3     float64
4     float64
       ...   
56    float64
57    float64
58    float64
59    float64
60     object
Length: 61, dtype: object

In [14]:
# as seen above that the last column which is the target column is categorical variable , lets handle it

df =  pd.get_dummies(df, '60', drop_first= True, dtype = int)
df.head()

0       1       2       3       4       5  ...      55      56      57      58      59  60_R
0  0.0200  0.0371  0.0428  0.0207  0.0954  0.0986  ...  0.0167  0.0180  0.0084  0.0090  0.0032     1
1  0.0453  0.0523  0.0843  0.0689  0.1183  0.2583  ...  0.0191  0.0140  0.0049  0.0052  0.0044     1
2  0.0262  0.0582  0.1099  0.1083  0.0974  0.2280  ...  0.0244  0.0316  0.0164  0.0095  0.0078     1
3  0.0100  0.0171  0.0623  0.0205  0.0205  0.0368  ...  0.0073  0.0050  0.0044  0.0040  0.0117     1
4  0.0762  0.0666  0.0481  0.0394  0.0590  0.0649  ...  0.0015  0.0072  0.0048  0.0107  0.0094     1

[5 rows x 61 columns]

In [18]:
df['60_R'].unique()

array([1, 0])

In [19]:
df.dtypes

0       float64
1       float64
2       float64
3       float64
4       float64
         ...   
56      float64
57      float64
58      float64
59      float64
60_R      int64
Length: 61, dtype: object

In [21]:
X = df.drop('60_R', axis= 1)
X.head()

0       1       2       3       4       5   ...      54      55      56      57      58      59
0  0.0200  0.0371  0.0428  0.0207  0.0954  0.0986  ...  0.0072  0.0167  0.0180  0.0084  0.0090  0.0032
1  0.0453  0.0523  0.0843  0.0689  0.1183  0.2583  ...  0.0094  0.0191  0.0140  0.0049  0.0052  0.0044
2  0.0262  0.0582  0.1099  0.1083  0.0974  0.2280  ...  0.0180  0.0244  0.0316  0.0164  0.0095  0.0078
3  0.0100  0.0171  0.0623  0.0205  0.0205  0.0368  ...  0.0085  0.0073  0.0050  0.0044  0.0040  0.0117
4  0.0762  0.0666  0.0481  0.0394  0.0590  0.0649  ...  0.0110  0.0015  0.0072  0.0048  0.0107  0.0094

[5 rows x 60 columns]

In [22]:
y = df['60_R']
y.head()

0    1
1    1
2    1
3    1
4    1
Name: 60_R, dtype: int64

In [48]:
y.value_counts()

60_R
0    111
1     97
Name: count, dtype: int64

#first split my data into train and test

In [23]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test  = train_test_split(X, y , test_size = 0.2, random_state= 1234, stratify = y  )

In [27]:
(X_train.shape, X_test.shape)

((166, 60), (42, 60))

#Lets build my Artificial Neural Networks (ANN) without a dropout layer

I will intentionally build build this model to overfit so I can see if drop_out regularization works

In [39]:
import tensorflow as tf
from tensorflow import keras

model = keras.Sequential([
    keras.layers.Dense(1000, input_shape = (60,), activation = 'relu'),
    keras.layers.Dense (1, activation = 'sigmoid')
])

model.compile(
    optimizer = 'adam',
    loss = 'binary_crossentropy',
    metrics = ['accuracy']
)


model.fit(X_train, y_train, epochs = 100, batch_size = 8)



Epoch 1/100


/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


21/21 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5279 - loss: 0.6918   
Epoch 2/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7492 - loss: 0.5931 
Epoch 3/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7436 - loss: 0.5548 
Epoch 4/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7793 - loss: 0.5052 
Epoch 5/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8433 - loss: 0.4590 
Epoch 6/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7525 - loss: 0.4475 
Epoch 7/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8044 - loss: 0.4288  
Epoch 8/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8450 - loss: 0.4307 
Epoch 9/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7841 - loss: 0.3990 
Epoch 10/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7906 - loss: 0.4774  
Epoch 11/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8031 - loss: 0.3839  
Epoch 12/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accur

#Evaluation and predicition using the model on new dataset

In [40]:
model.evaluate(X_test, y_test)

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7738 - loss: 0.4726  


[0.46438106894493103, 0.7857142686843872]

In [45]:
y_preds = np.round(model.predict(X_test))
y_preds[:5]

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step 


array([[0.],
       [0.],
       [0.],
       [1.],
       [1.]], dtype=float32)

the model performed not too poorly on the test set , I guess ? Do you guess the same as me?

In [46]:
from sklearn.metrics import classification_report , confusion_matrix

print(classification_report(y_test, y_preds))



              precision    recall  f1-score   support

           0       0.78      0.82      0.80        22
           1       0.79      0.75      0.77        20

    accuracy                           0.79        42
   macro avg       0.79      0.78      0.78        42
weighted avg       0.79      0.79      0.79        42



#Now, Building the ANN model with a dropout layer to see if i can get a better performance


In [49]:
X_train.shape

(166, 60)

In [52]:
model1 = keras.Sequential([
    keras.layers.Dense(10000, input_shape = (60,), activation = 'relu'),
    keras.layers.Dropout(0.5),
    keras.layers.Dense(1, activation = 'sigmoid')
])

model1.compile(
    optimizer ='adam',
    loss = 'binary_crossentropy',
    metrics = ['accuracy']
)

model1.fit(X_train, y_train, epochs = 100, batch_size = 8)

Epoch 1/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - accuracy: 0.5416 - loss: 0.6883
Epoch 2/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6290 - loss: 0.6114
Epoch 3/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.5781 - loss: 0.6532
Epoch 4/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6985 - loss: 0.5805
Epoch 5/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8290 - loss: 0.4963
Epoch 6/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8224 - loss: 0.4414
Epoch 7/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7390 - loss: 0.4963
Epoch 8/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8073 - loss: 0.4140
Epoch 9/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8492 - loss: 0.3996
Epoch 10/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8103 - loss: 0.4270
Epoch 11/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8059 - loss: 0.4652
Epoch 12/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy

In [54]:
model1.evaluate(X_test, y_test)

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7579 - loss: 0.5399


[0.5347761511802673, 0.761904776096344]

In [59]:
y_preds = np.round(model1.predict(X_test))
y_preds[:9]

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step 


array([[0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.]], dtype=float32)

In [60]:
from sklearn.metrics import classification_report , confusion_matrix

print(classification_report(y_test, y_preds))

              precision    recall  f1-score   support

           0       0.80      0.73      0.76        22
           1       0.73      0.80      0.76        20

    accuracy                           0.76        42
   macro avg       0.76      0.76      0.76        42
weighted avg       0.77      0.76      0.76        42



In [ ]:
#Well , there wasn't any much difference , it seems that the f1-score of the model without dropout performed well , but the class 1 seems to do better  in this case in the recall